# Generated by Django 4.2.7 on 2025-06-16 07:13

import announcements.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_options_alter_announcement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', announcements.utils.fields.EncryptedTextField()),
                ('recipients', announcements.utils.fields.EncryptedJsonField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', announcements.utils.fields.EncryptedCharField(max_length=255)),
                ('email', announcements.utils.fields.EncryptedEmailField(max_length=255)),
                ('personal_info', announcements.utils.fields.EncryptedJsonField(blank=True, null=True)),
                ('notes', announcements.utils.fields.EncryptedTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=announcements.utils.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
